// <auto-generated />
using System;
using Kursach_CorpHubPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kursach_CorpHubPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251227130008_Migration4")]
    partial class Migration4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Уникальный идентификатор отдела");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Дата создания записи");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Описание отдела и его функций");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Название отдела");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Departments_CreatedAt");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("IX_Departments_ManagerId")
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Name_Unique")
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Departments", "dbo", t =>
                        {
                            t.HasComment("Таблица отделов компании");

                            t.HasCheckConstraint("CK_Department_Name_HasLetters", "[Name] LIKE N'%[A-Za-z]%' OR [Name] LIKE N'%[А-Яа-я]%'");

                            t.HasCheckConstraint("CK_Department_Name_Length", "LEN([Name]) >= 2 AND LEN([Name]) <= 100");
                        });
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Уникальный идентификатор должности");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Описание должностных обязанностей");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("Уровень зарплаты для должности");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Название должности");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("IX_Positions_Title_Unique")
                        .HasFilter("[Title] IS NOT NULL");

                    b.ToTable("Positions", "dbo", t =>
                        {
                            t.HasComment("Справочник должностей компании");

                            t.HasCheckConstraint("CK_Position_Salary_Max", "[Salary] IS NULL OR [Salary] <= 10000000");

                            t.HasCheckConstraint("CK_Position_Salary_Positive", "[Salary] IS NULL OR [Salary] >= 0");

                            t.HasCheckConstraint("CK_Position_Title_HasLetters", "[Title] LIKE N'%[A-Za-z]%' OR [Title] LIKE N'%[А-Яа-я]%'");

                            t.HasCheckConstraint("CK_Position_Title_Length", "LEN([Title]) >= 2 AND LEN([Title]) <= 100");
                        });
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Уникальный идентификатор задачи");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2")
                        .HasComment("Дата завершения");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Дата создания");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Описание задачи");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasComment("Срок выполнения");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("Medium")
                        .HasComment("Приоритет задачи");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Результат выполнения");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Дата начала");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("New")
                        .HasComment("Статус задачи");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Название задачи");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Tasks_CreatedAt");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("IX_Tasks_CreatedBy");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Tasks_DueDate")
                        .HasFilter("[DueDate] IS NOT NULL");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_Tasks_Priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tasks_Status")
                        .HasFilter("[Status] IN ('New', 'InProgress')");

                    b.HasIndex("AssignedToId", "Status")
                        .HasDatabaseName("IX_Tasks_AssignedTo_Status");

                    b.HasIndex("Status", "Priority", "DueDate")
                        .HasDatabaseName("IX_Tasks_Status_Priority_DueDate");

                    b.ToTable("Tasks", "dbo", t =>
                        {
                            t.HasComment("Таблица задач и поручений");

                            t.HasCheckConstraint("CK_Task_Dates_Logical", "([StartDate] IS NULL OR [StartDate] >= [CreatedAt]) AND\r\n                        ([CompletedDate] IS NULL OR [CompletedDate] >= [StartDate]) AND\r\n                        ([DueDate] IS NULL OR [DueDate] >= [CreatedAt])");

                            t.HasCheckConstraint("CK_Task_Priority_Values", "[Priority] IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("CK_Task_Title_Length", "LEN([Title]) >= 3 AND LEN([Title]) <= 128");
                        });
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Уникальный идентификатор пользователя");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Адрес проживания");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Дата создания записи");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasComment("Дата рождения");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Электронная почта (уникальная)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Имя пользователя");

                    b.Property<DateTime>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Дата приема на работу");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Фамилия пользователя");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Отчество пользователя");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Хеш пароля");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Соль для пароля");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Номер телефона");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("URL фотографии профиля");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Employee")
                        .HasComment("Роль пользователя в системе");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active")
                        .HasComment("Статус учетной записи");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("date")
                        .HasComment("Дата увольнения");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("Дата последнего обновления");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Users_DepartmentId")
                        .HasFilter("[DepartmentId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("HireDate")
                        .HasDatabaseName("IX_Users_HireDate");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_Users_PositionId")
                        .HasFilter("[PositionId] IS NOT NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status")
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("DepartmentId", "Status")
                        .HasDatabaseName("IX_Users_Department_Status");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Users_Name");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LastName", "FirstName"), new[] { "MiddleName", "Email" });

                    b.ToTable("Users", "dbo", t =>
                        {
                            t.HasComment("Таблица пользователей (сотрудников) системы");

                            t.HasCheckConstraint("CK_User_Email_Format", "[Email] LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_User_Phone_Format", "[PhoneNumber] IS NULL OR LEN([PhoneNumber]) >= 10");
                        });
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.Department", b =>
                {
                    b.HasOne("Kursach_CorpHubPortal.Data.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Departments_Users_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.Task", b =>
                {
                    b.HasOne("Kursach_CorpHubPortal.Data.Entities.User", "AssignedTo")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Users_AssignedTo");

                    b.HasOne("Kursach_CorpHubPortal.Data.Entities.User", "CreatedBy")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Users_CreatedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.User", b =>
                {
                    b.HasOne("Kursach_CorpHubPortal.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_Departments");

                    b.HasOne("Kursach_CorpHubPortal.Data.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_Positions");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Kursach_CorpHubPortal.Data.Entities.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
